let manifest = [
    {
        src:"spritesheet.js",
        id:"spritesheet"
    },
    {
        src:"lib/keyUp.ogg",
        id:"keyUpSound",
        data:4
    },
    {
        src:"lib/keyDown.ogg",
        id:"keyDownSound",
        data:4
    },
    {
        src:"lib/recording.wav",
        id:"menuMusic",
        data:4
    },
    {
        src:"lib/recording2.wav",
        id:"gameMusic",
        data:4
    },
    {
        src:"lib/swoosh.mp3",
        id:"swoosh",
        data:4
    },
    {
        src:"lib/grapple.wav",
        id:"grapple",
        data:4
    },
    {
        src:"lib/trombone.wav",
        id:"trombone",
        data:4
    },
    {
        src:"lib/yahoo.wav",
        id:"yahoo",
        data:4
    },
    {
        src:"lib/fireworks.wav",
        id:"fireworks",
        data:4
    },
    {
        src:"lib/applause.wav",
        id:"applause",
        data:4
    },
    {
        src:"lib/startRound.wav",
        id:"startRound",
        data:4
    },
    {
        src:"lib/ouch.wav",
        id:"ouch",
        data:4
    },
    {
        src:"lib/yahoo.wav",
        id:"yahoo",
        data:4
    }
];