let manifest = [
    {
        src:"spritesheet.js",
        id:"spritesheet"
    },
    {
        src:"lib/keyUp.ogg",
        id:"keyUpSound",
        data:4
    },
    {
        src:"lib/keyDown.ogg",
        id:"keyDownSound",
        data:4
    },
    {
        src:"lib/recording.wav",
        id:"menuMusic",
        data:4
    },
    {
        src:"lib/recording2.wav",
        id:"gameMusic",
        data:4
    }
];